title: "Heat Pump From The Cold"
description: "40 years of heat pump innovation — L'évolution de la pompe à chaleur sur 40 ans"
theme: minima
lang: fr
baseurl: "/HeatPumpFromTheCold"
url: "https://papymakers.github.io"

minima:
  header_pages: []
